site:
  title: Joshua Smith's Homepage
  url: https://giliath.org
  start_page: 240sx::background.adoc
content:
  sources:
  - url: .
    start_path: 240sx
    branches: HEAD
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true